import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const checkedAt = new Date().toISOString().slice(0, 10);

const sourcesPath = path.join(process.cwd(), "src", "data", "providerSources.json");
const providerSources = JSON.parse(await readFile(sourcesPath, "utf8"));
const sourceById = new Map(providerSources.map((source) => [source.id, source]));

const mtok = "USD / 1M tokens";

const price = (label, value, unit = mtok) => ({ label, value, unit });

const rows = [
  {
    id: "openai-gpt-5-5",
    provider: "OpenAI",
    model: "GPT-5.5",
    country: "United States",
    region: "US",
    modality: "Reasoning",
    contextWindow: "Vendor calculator lists GPT-5 family context options",
    input: price("Input", 5),
    cachedInput: price("Cached input", 0.5),
    output: price("Output", 30),
    extra: [],
    notes: "Frontier model for coding and professional work; standard processing price.",
    sourceKey: "openai",
    sourceLabel: "OpenAI API pricing",
  },
  {
    id: "openai-gpt-5-4",
    provider: "OpenAI",
    model: "GPT-5.4",
    country: "United States",
    region: "US",
    modality: "Reasoning",
    contextWindow: "<270K standard pricing note",
    input: price("Input", 2.5),
    cachedInput: price("Cached input", 0.25),
    output: price("Output", 15),
    extra: [],
    notes: "More affordable frontier model; batch mode is advertised separately at a discount.",
    sourceKey: "openai",
    sourceLabel: "OpenAI API pricing",
  },
  {
    id: "openai-gpt-5-4-mini",
    provider: "OpenAI",
    model: "GPT-5.4 mini",
    country: "United States",
    region: "US",
    modality: "Text",
    contextWindow: "<270K standard pricing note",
    input: price("Input", 0.75),
    cachedInput: price("Cached input", 0.075),
    output: price("Output", 4.5),
    extra: [],
    notes: "Mini model positioned for coding, computer use, and subagents.",
    sourceKey: "openai",
    sourceLabel: "OpenAI API pricing",
  },
  {
    id: "openai-gpt-realtime-2",
    provider: "OpenAI",
    model: "GPT-Realtime-2",
    country: "United States",
    region: "US",
    modality: "Audio",
    contextWindow: "Realtime session",
    input: price("Audio input", 32),
    cachedInput: price("Audio cached input", 0.4),
    output: price("Audio output", 64),
    extra: [price("Text input", 4), price("Text output", 24), price("Image input", 5)],
    notes: "Realtime voice model with separate audio, text, and image token rates.",
    sourceKey: "openai",
    sourceLabel: "OpenAI API pricing",
  },
  {
    id: "openai-gpt-image-2",
    provider: "OpenAI",
    model: "GPT-Image-2",
    country: "United States",
    region: "US",
    modality: "Image",
    contextWindow: "Image tokens",
    input: price("Image input", 8),
    cachedInput: price("Image cached input", 2),
    output: price("Image output", 30),
    extra: [price("Text input", 5), price("Text cached input", 1.25)],
    notes: "Image generation model; actual image cost depends on tokenized size.",
    sourceKey: "openai",
    sourceLabel: "OpenAI API pricing",
  },
  {
    id: "anthropic-opus-4-8",
    provider: "Anthropic",
    model: "Claude Opus 4.8",
    country: "United States",
    region: "US",
    modality: "Reasoning",
    contextWindow: "1M tokens",
    input: price("Input", 5),
    cachedInput: price("Cache read", 0.5),
    output: price("Output", 25),
    extra: [price("Cache write", 6.25)],
    notes: "Complex agentic coding and enterprise work; 5-minute prompt cache TTL.",
    sourceKey: "anthropic",
    sourceLabel: "Claude API pricing",
  },
  {
    id: "anthropic-sonnet-4-6",
    provider: "Anthropic",
    model: "Claude Sonnet 4.6",
    country: "United States",
    region: "US",
    modality: "Text",
    contextWindow: "1M tokens",
    input: price("Input", 3),
    cachedInput: price("Cache read", 0.3),
    output: price("Output", 15),
    extra: [price("Cache write", 3.75)],
    notes: "Balanced intelligence, cost, and speed; US-only inference is listed at 1.1x.",
    sourceKey: "anthropic",
    sourceLabel: "Claude API pricing",
  },
  {
    id: "anthropic-haiku-4-5",
    provider: "Anthropic",
    model: "Claude Haiku 4.5",
    country: "United States",
    region: "US",
    modality: "Text",
    contextWindow: "Vendor docs",
    input: price("Input", 1),
    cachedInput: price("Cache read", 0.1),
    output: price("Output", 5),
    extra: [price("Cache write", 1.25)],
    notes: "Cost-efficient Claude model for lower-latency workloads.",
    sourceKey: "anthropic",
    sourceLabel: "Claude API pricing",
  },
  {
    id: "anthropic-web-search",
    provider: "Anthropic",
    model: "Claude web search",
    country: "United States",
    region: "US",
    modality: "Tooling",
    contextWindow: "Per tool use",
    input: null,
    cachedInput: null,
    output: price("Web search", 10, "USD / 1K searches"),
    extra: [],
    notes: "Search cost is in addition to normal token charges.",
    sourceKey: "anthropic",
    sourceLabel: "Claude API pricing",
  },
  {
    id: "google-gemini-3-flash-preview",
    provider: "Google",
    model: "Gemini 3 Flash Preview",
    country: "United States",
    region: "Global",
    modality: "Multimodal",
    contextWindow: "Vendor docs",
    input: price("Text/image/video input", 0.5),
    cachedInput: price("Context cache", 0.05),
    output: price("Output incl. thinking", 3),
    extra: [price("Audio input", 1), price("Audio cache", 0.1), price("Search grounding", 14, "USD / 1K queries after free tier")],
    notes: "Paid standard tier; batch and flex prices are lower.",
    sourceKey: "google",
    sourceLabel: "Gemini API pricing",
  },
  {
    id: "google-gemini-3-pro-image",
    provider: "Google",
    model: "Gemini 3 Pro Image",
    country: "United States",
    region: "Global",
    modality: "Image",
    contextWindow: "Image generation",
    input: price("Text/image input", 2),
    cachedInput: null,
    output: price("Image output", 120),
    extra: [price("Text output", 12), price("1K/2K image equivalent", 0.134, "USD / image")],
    notes: "Native image generation; text input/output follows Gemini 3.1 Pro pricing note.",
    sourceKey: "google",
    sourceLabel: "Gemini API pricing",
  },
  {
    id: "google-gemini-3-1-flash-tts",
    provider: "Google",
    model: "Gemini 3.1 Flash TTS Preview",
    country: "United States",
    region: "Global",
    modality: "Audio",
    contextWindow: "25 audio tokens/sec",
    input: price("Text input", 1),
    cachedInput: null,
    output: price("Audio output", 20),
    extra: [],
    notes: "Text-to-speech model; audio token conversion listed as 25 tokens per second.",
    sourceKey: "google",
    sourceLabel: "Gemini API pricing",
  },
  {
    id: "xai-grok-4-3",
    provider: "xAI",
    model: "Grok 4.3",
    country: "United States",
    region: "US",
    modality: "Text",
    contextWindow: "1M tokens",
    input: price("Input", 1.25),
    cachedInput: price("Cached input", 0.2),
    output: price("Output", 2.5),
    extra: [],
    notes: "xAI default chat model per current pricing table.",
    sourceKey: "xai",
    sourceLabel: "xAI pricing",
  },
  {
    id: "xai-grok-build-0-1",
    provider: "xAI",
    model: "Grok Build 0.1",
    country: "United States",
    region: "US",
    modality: "Reasoning",
    contextWindow: "256K tokens",
    input: price("Input", 1),
    cachedInput: price("Cached input", 0.2),
    output: price("Output", 2),
    extra: [],
    notes: "Coding-focused model.",
    sourceKey: "xai",
    sourceLabel: "xAI pricing",
  },
  {
    id: "xai-grok-imagine-video",
    provider: "xAI",
    model: "Grok Imagine Video",
    country: "United States",
    region: "US",
    modality: "Video",
    contextWindow: "Per generated second",
    input: price("Video input", 0.01, "USD / sec"),
    cachedInput: null,
    output: price("480p output", 0.05, "USD / sec"),
    extra: [price("720p output", 0.07, "USD / sec"), price("Image input", 0.002, "USD / image")],
    notes: "Text, image, or video to video model.",
    sourceKey: "xai",
    sourceLabel: "xAI pricing",
  },
  {
    id: "xai-voice-realtime",
    provider: "xAI",
    model: "Grok Voice Realtime",
    country: "United States",
    region: "US",
    modality: "Audio",
    contextWindow: "Realtime session",
    input: null,
    cachedInput: null,
    output: price("Realtime voice", 0.05, "USD / min"),
    extra: [price("TTS", 15, "USD / 1M chars"), price("STT REST", 0.1, "USD / hr")],
    notes: "Voice API prices are unit-based rather than token-only.",
    sourceKey: "xai",
    sourceLabel: "xAI pricing",
  },
  {
    id: "deepseek-v4-flash-non-thinking",
    provider: "DeepSeek",
    model: "deepseek-v4-flash non-thinking",
    country: "China",
    region: "China",
    modality: "Text",
    contextWindow: "Vendor docs",
    input: price("Cache miss input", 0.14),
    cachedInput: price("Cache hit input", 0.0028),
    output: price("Output", 0.28),
    extra: [],
    notes: "Compatibility alias: deepseek-chat until the listed deprecation date.",
    sourceKey: "deepseek",
    sourceLabel: "DeepSeek models and pricing",
  },
  {
    id: "deepseek-v4-flash-thinking",
    provider: "DeepSeek",
    model: "deepseek-v4-flash thinking",
    country: "China",
    region: "China",
    modality: "Reasoning",
    contextWindow: "Vendor docs",
    input: price("Cache miss input", 0.435),
    cachedInput: price("Cache hit input", 0.003625),
    output: price("Output", 0.87),
    extra: [],
    notes: "Compatibility alias: deepseek-reasoner until the listed deprecation date.",
    sourceKey: "deepseek",
    sourceLabel: "DeepSeek models and pricing",
  },
  {
    id: "alibaba-qwen3-5-flash",
    provider: "Alibaba Cloud",
    model: "qwen3.5-flash",
    country: "China",
    region: "Global / China",
    modality: "Text",
    contextWindow: "<=128K tier shown",
    input: price("Input", 0.029),
    cachedInput: null,
    output: price("Output", 0.287),
    extra: [],
    notes: "Tiered pricing increases for larger request sizes; row shows the first tier.",
    sourceKey: "alibaba",
    sourceLabel: "Alibaba Model Studio pricing",
  },
  {
    id: "alibaba-qwen-flash",
    provider: "Alibaba Cloud",
    model: "qwen-flash",
    country: "China",
    region: "Global / China",
    modality: "Text",
    contextWindow: "<=128K tier shown",
    input: price("Input", 0.022),
    cachedInput: null,
    output: price("Output", 0.216),
    extra: [],
    notes: "Tiered pricing shown for qwen-flash first request-size band.",
    sourceKey: "alibaba",
    sourceLabel: "Alibaba Model Studio pricing",
  },
  {
    id: "alibaba-kimi-k2-5",
    provider: "Alibaba Cloud",
    model: "kimi-k2.5",
    country: "China",
    region: "Chinese Mainland",
    modality: "Text",
    contextWindow: "Chinese Mainland deployment only",
    input: price("Input", 0.574),
    cachedInput: null,
    output: price("Output", 3.011),
    extra: [],
    notes: "Endpoint, data storage, and inference resources are listed as restricted to Chinese Mainland.",
    sourceKey: "alibaba",
    sourceLabel: "Alibaba Model Studio pricing",
  },
  {
    id: "zai-glm-5-2",
    provider: "Z.AI",
    model: "GLM-5.2",
    country: "China",
    region: "Global / China",
    modality: "Reasoning",
    contextWindow: "1M tokens with [1m] suffix",
    input: null,
    cachedInput: null,
    output: price("Lite plan starts", 18, "USD / month"),
    extra: [
      price("Lite 5-hour quota", 80, "approx prompts"),
      price("Lite weekly quota", 400, "approx prompts"),
    ],
    notes:
      "Official docs list GLM-5.2 for GLM Coding Plan users; the general API pricing table does not list a standalone per-token GLM-5.2 price yet.",
    sourceKey: "zai",
    sourceLabel: "Z.AI GLM Coding Plan overview",
  },
  {
    id: "moonshot-kimi-k2-7-code",
    provider: "Moonshot AI",
    model: "Kimi K2.7 Code",
    country: "China",
    region: "Global",
    modality: "Multimodal",
    contextWindow: "256K tokens",
    input: price("Input", 0.95),
    cachedInput: price("Cache hit", 0.19),
    output: price("Output", 4),
    extra: [],
    notes:
      "Official Kimi platform describes K2.7 Code as a coding-focused multimodal model with text, image, and video input plus thinking modes.",
    sourceKey: "moonshot",
    sourceLabel: "Kimi K2.7 Code pricing",
  },
  {
    id: "mistral-large-3",
    provider: "Mistral",
    model: "Mistral Large 3",
    country: "France",
    region: "Europe",
    modality: "Multimodal",
    contextWindow: "Vendor docs",
    input: price("Input", 0.5),
    cachedInput: null,
    output: price("Output", 1.5),
    extra: [],
    notes: "Open-weight, general-purpose multimodal and multilingual model.",
    sourceKey: "mistral",
    sourceLabel: "Mistral pricing",
  },
  {
    id: "mistral-medium-3-5",
    provider: "Mistral",
    model: "Mistral Medium 3.5",
    country: "France",
    region: "Europe",
    modality: "Reasoning",
    contextWindow: "Vendor docs",
    input: price("Input", 1.5),
    cachedInput: null,
    output: price("Output", 7.5),
    extra: [],
    notes: "Flagship model for instruction following, reasoning, and coding.",
    sourceKey: "mistral",
    sourceLabel: "Mistral pricing",
  },
  {
    id: "mistral-small-4",
    provider: "Mistral",
    model: "Mistral Small 4",
    country: "France",
    region: "Europe",
    modality: "Text",
    contextWindow: "Vendor docs",
    input: price("Input", 0.1),
    cachedInput: null,
    output: price("Output", 0.3),
    extra: [],
    notes: "Cost-sensitive multimodal, multilingual model.",
    sourceKey: "mistral",
    sourceLabel: "Mistral pricing",
  },
  {
    id: "mistral-ocr-3",
    provider: "Mistral",
    model: "OCR 3",
    country: "France",
    region: "Europe",
    modality: "Document",
    contextWindow: "Per page",
    input: null,
    cachedInput: null,
    output: price("OCR", 2, "USD / 1K pages"),
    extra: [price("Annotations", 3, "USD / 1K pages")],
    notes: "Document extraction and understanding endpoint.",
    sourceKey: "mistral",
    sourceLabel: "Mistral pricing",
  },
  {
    id: "cohere-aya-expanse",
    provider: "Cohere",
    model: "Aya Expanse 8B/32B",
    country: "Canada",
    region: "North America",
    modality: "Text",
    contextWindow: "Vendor docs",
    input: price("Input", 0.5),
    cachedInput: null,
    output: price("Output", 1.5),
    extra: [],
    notes: "Multilingual research models available through the API.",
    sourceKey: "cohere",
    sourceLabel: "Cohere pricing",
  },
  {
    id: "cohere-rerank-4-pro-vault",
    provider: "Cohere",
    model: "Rerank 4 Pro - Model Vault",
    country: "Canada",
    region: "North America",
    modality: "Rerank",
    contextWindow: "Dedicated instance",
    input: null,
    cachedInput: null,
    output: price("Medium instance", 5, "USD / hr"),
    extra: [price("Large instance", 10, "USD / hr")],
    notes: "Dedicated managed deployment pricing, not shared pay-as-you-go token pricing.",
    sourceKey: "cohere",
    sourceLabel: "Cohere pricing",
  },
  {
    id: "cohere-embed-4-vault",
    provider: "Cohere",
    model: "Embed 4 - Model Vault",
    country: "Canada",
    region: "North America",
    modality: "Embedding",
    contextWindow: "Dedicated instance",
    input: null,
    cachedInput: null,
    output: price("Small instance", 4, "USD / hr"),
    extra: [price("Medium instance", 5, "USD / hr")],
    notes: "Dedicated managed deployment pricing for retrieval workloads.",
    sourceKey: "cohere",
    sourceLabel: "Cohere pricing",
  },
  {
    id: "elevenlabs-flash-turbo",
    provider: "ElevenLabs",
    model: "Flash / Turbo TTS",
    country: "United States",
    region: "US",
    modality: "Audio",
    contextWindow: "Per character",
    input: null,
    cachedInput: null,
    output: price("Text to speech", 0.05, "USD / 1K chars"),
    extra: [],
    notes: "Niche voice API with low-latency text-to-speech pricing.",
    sourceKey: "elevenlabs",
    sourceLabel: "ElevenLabs API pricing",
  },
];

async function checkSource(url) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 10_000);

  try {
    const response = await fetch(url, {
      signal: controller.signal,
      headers: {
        "user-agent": "ai-models-cost-board/0.1 (+local refresh script)",
      },
    });

    return response.ok ? "checked" : "source-unavailable";
  } catch {
    return "source-unavailable";
  } finally {
    clearTimeout(timeout);
  }
}

async function checkProviderSource(source) {
  for (const page of source.pages) {
    const status = await checkSource(page.url);

    if (status === "checked") {
      return status;
    }
  }

  return "source-unavailable";
}

const sourceStatuses = Object.fromEntries(
  await Promise.all(
    providerSources.map(async (source) => {
      return [source.id, await checkProviderSource(source)];
    })
  )
);

const generatedRows = rows.map(({ sourceKey, ...row }) => ({
  ...row,
  sourceUrl: (sourceById.get(sourceKey)?.pages.find((page) => page.primary) ?? sourceById.get(sourceKey)?.pages[0])
    ?.url,
  sourceStatus: sourceStatuses[sourceKey] ?? "manual",
  lastChecked: checkedAt,
}));

const target = path.join(process.cwd(), "src", "data", "pricing.generated.ts");
await mkdir(path.dirname(target), { recursive: true });
await writeFile(
  target,
  `import type { PricingRow } from "../types";\n\nexport const generatedAt = ${JSON.stringify(
    checkedAt
  )};\n\nexport const pricingRows: PricingRow[] = ${JSON.stringify(
    generatedRows,
    null,
    2
  )};\n`,
  "utf8"
);

const unavailable = Object.entries(sourceStatuses)
  .filter(([, status]) => status !== "checked")
  .map(([key]) => key);

console.log(`Regenerated ${generatedRows.length} pricing rows.`);
console.log(`Checked ${providerSources.length} official provider sources on ${checkedAt}.`);
if (unavailable.length) {
  console.log(`Source checks needing review: ${unavailable.join(", ")}`);
}

process.exit(0);
